# Numpy 簡介
NumPy is the fundamental package for scientific computing with Python.

It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

The official website of Numpy is [here](https://numpy.org/).


In [2]:
import numpy as np

### 產生 numpy 的串列
Array creation

In [3]:
#lst is a one dimensional array
lst = np.array([1,2,4,8,7])
print(type(lst))
print(lst)

<class 'numpy.ndarray'>
[1 2 4 8 7]


## 使用規則產生串列

``numpy.arange([start, ]stop, [step, ]dtype=None)`` [document](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)`` (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

**arange**(起始, 終結, 步進值)

**arange**(1, 20) # 產生 1,2,...,19 的串列

**arange**(1, 20, 2) # 產生 1,3,5,...,19 的串列

In [6]:
lst2 = np.arange(1,20,2)
print(lst2)

[ 1  3  5  7  9 11 13 15 17 19]


### 產生一序列的資料
``numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)``[document](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html#numpy.linspace)

Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval ``[start, stop]``.

The endpoint of the interval can optionally be excluded.

Generate 50 points that are evently spreaded in the range [1.0, 3.0]

在 [1.0, 3.0] 區間中，均勻地產生 50 個資料點

**linspace**(1.0, 3.0, num=50)  

註：linspace 和 arange 很像，不一樣處在於，linespace 允許產生小數點的數，但 arange 所產生的數都是整數。更清楚地說，arange 中的步進值都是整數，不可以是小數，但 linespace 可以是小數。

In [19]:
#include endpoint (包含上限值)
lst1 = np.linspace(1.0, 3.0, num=12)
print(lst1)
#exclude endpoint (不包含上限值)
lst2 = np.linspace(1.0, 3.0, num=12, endpoint=False)
print(lst2)

[1.         1.18181818 1.36363636 1.54545455 1.72727273 1.90909091
 2.09090909 2.27272727 2.45454545 2.63636364 2.81818182 3.        ]
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333]


### N-dimensional array creation

建立 2 維的陣列

np.array([
[1,2],
[3,4]
])

In [20]:
arr2 = np.array([
    [1,2],
    [3,4]
])
print(arr2)
#ndim returns the number of dimensions of the array (ndim 會回傳這個陣列有幾個維度)
print(arr2.ndim)

[[1 2]
 [3 4]]
2


In [10]:
#shape returns a tuple of array dimensions
#arr2 is a 2*2 array
arr2.shape

(2, 2)

In [26]:
#lst1 is an one-dimensional array that contains 12 elements (lst1 是一個一維的陣列，其包含 12 個元素)
print(lst1.shape)

(3, 4)


### Number of elements in an array

取得陣列中元素個數

In [27]:
lst = np.array([1,4,7,6])
print(f"The number of elements in lst is {lst.size}")

The number of elements in lst is 4


In [29]:
arr3 = np.arange(1,11)
arr4 = arr3.reshape(2,5)
print(f"The shape of arr4 is {arr4.shape}")
print(f"The number of elements of arr4 is {arr3.size}")

The shape of arr4 is (2, 5)
The number of elements of arr4 is 10


### Use reshape to change the dimension of an array

Gives a new shape to an array without changing its data.

使用 reshape 這個指令來改變 array 的維度

In [22]:
#lst1 is a one dimensional array with 12 elements 
#lst1 是一個一維的陣列，包含了 12 個元素
print(lst1)
print(lst1.shape)
print(f"lst1 的維度為 {lst1.ndim}")
#將 lst1 改成為一個 3*4 的二維陣列 (有三個 rows，以及 4 個 columns)
lst1 = lst1.reshape(3,4)
print(lst1)
print(lst1.shape)
print(f"lst1 的維度為 {lst1.ndim}")

[1.         1.18181818 1.36363636 1.54545455 1.72727273 1.90909091
 2.09090909 2.27272727 2.45454545 2.63636364 2.81818182 3.        ]
(12,)
lst1 的維度為 1
[[1.         1.18181818 1.36363636 1.54545455]
 [1.72727273 1.90909091 2.09090909 2.27272727]
 [2.45454545 2.63636364 2.81818182 3.        ]]
(3, 4)
lst1 的維度為 2


### 將運算指定到所有的元素

Numpy 會把所有的運算都指定到串中所有的元素上。

所以不用撰寫迴圈！


In [8]:
# 所有元素加1 
lst = np.arange(1,10)
print(lst)
lst = lst + 1
print(lst)

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]


In [9]:
# 所有元素都取指數次方
lst = np.arange(1, 10)
print(lst)
lst = np.exp(lst)
print(lst)

[1 2 3 4 5 6 7 8 9]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [25]:
#Apply floor to each element of lst
lst = np.linspace(1.0, 5.0, num=20)
print(lst)
lst2 = np.floor(lst)
print(lst2)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]
[1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 4. 4. 4. 4. 5.]


In [10]:
np.sum(np.arange(1,10)) #計算 1+2+3+...+9

45

In [11]:
np.mean(np.arange(1,10)) #計算 (1,2,3,...,9) 的平均
#np.median 取中位數
#np.var 取變異數
#np.std 取標準差

5.0

## 陣列運算

陣列運算分兩種:
- element-wise (逐元素運算)
- array (maxtrix) operation (陣列運算)

### Element-wise (逐元素運算)

Element-wise operator is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element $i, j$ is the product of elements $i, j$ of the original two matrices.

逐元素運算指的是兩個陣列的運算，這兩個陣列要有相同的維度。例如都是 $2 \times 2$ 的陣列。

假設目前有兩個陣列 $A$ 及 $B$，它們要做逐元素運算，那 $A$ 的第 $i,j$ 個元素 (令其為 $A[i,j]$) 會和 $B[i,j]$ 做運算，得到結果。

下圖展示了 element-wise 的陣列相加，可以看到 $A[0,0] + B[0,0] == C[0,0]$

![](elementwise.png)

In [30]:
#逐元素相加
lst1 = np.array([1,2,3,4])
lst2 = np.array([3,3,3,3])
lst3 = lst1 + lst2
print(lst3)

[4 5 6 7]


In [31]:
#逐元素相除
lst3 = lst1 / lst2
print(lst3)

[0.33333333 0.66666667 1.         1.33333333]


In [35]:
#element-wise multiply
lst3 = lst1 * lst2
print(lst3)

[ 3  6  9 12]


In [36]:
#element-wise addition for 2D array
arr1 = np.array([
    [1,2],
    [3,4]
])

arr2 = np.array([
    [3,3],
    [3,3]
])

arr3 = arr1 + arr2
print(arr3)

[[4 5]
 [6 7]]


## Matrix operations

There three common matrix (array) operations:
- Production
- Transpose
- Inverse

常見的陣列的運算有三種

- 陣列相乘
- 陣列轉秩
- 反矩陣

![](arrayproduction.png)

### Array production

In [37]:
arr1 = np.array([
    [3,1,2],
    [0,1,5]
])

arr2 = np.array([
    [4,3],
    [1,1],
    [6,0]
])

arr3 = np.dot(arr1, arr2)

print(arr3)

[[25 10]
 [31  1]]


### Array transpose

In [38]:
print(arr2)
arr3 = arr2.T
print(arr3)

[[4 3]
 [1 1]
 [6 0]]
[[4 1 6]
 [3 1 0]]


### Inverse

In [39]:
arr1 = np.array([
    [0,1,2],
    [1,1,4],
    [2,-1,0]
])

arr2 = np.linalg.inv(arr1)
print(arr2)

[[ 2.  -1.   1. ]
 [ 4.  -2.   1. ]
 [-1.5  1.  -0.5]]


## Access the elements in an array

存取 array 中的元素

In [33]:
lst = np.array([1,4,7,16,24,35])
print(lst[0]) #Note: the index for the first element is 0
print(lst[1])

1
4


In [34]:
#Iterate each element in lst using the for loop
for v in lst:
    print(v)

1
4
7
16
24
35


In [42]:
arr1 = np.array([
    [0,1,2],
    [1,1,4],
    [2,-1,0]
])

print(f"arr[0][0] = {arr1[0][0]}")
print(f"arr[0][1] = {arr1[0][1]}")
print(f"arr[1][1] = {arr1[1][1]}")

arr[0][0] = 0
arr[0][1] = 1
arr[1][1] = 1


In [48]:
arr1 = np.array([
    [0,1,2],
    [1,1,4],
    [2,-1,0]
])

print(f"arr1[0] = {arr1[0]}")
print(f"arr1[1] = {arr1[1]}")
print(f"arr1[2] = {arr1[2]}")
print(f"The first row of arr1 is {arr1[0,:]}")
print(f"The second row of arr1 is {arr1[1,:]}")
print(f"The third row of arr1 is {arr1[2,:]}")

arr1[0] = [0 1 2]
arr1[1] = [1 1 4]
arr1[2] = [ 2 -1  0]
The first row of arr1 is [0 1 2]
The second row of arr1 is [1 1 4]
The third row of arr1 is [ 2 -1  0]


In [47]:
arr1 = np.array([
    [0,1,2],
    [1,1,4],
    [2,-1,0]
])

print(f"The first column of arr1 is {arr1[:,0]}")
print(f"The second column of arr1 is {arr1[:,1]}")
print(f"The third column of arr1 is {arr1[:,2]}")

The first column of arr1 is [0 1 2]
The second column of arr1 is [ 1  1 -1]
The third column of arr1 is [2 4 0]
